### ISSUE TITLE
Session favoriting

### ISSUE THREAD

**Issue by nickswalker** [utcsmad/uMAD-iOS#22]
Need to allow users to star any non-overlapping sessions.

**Comment by jessetipton** [comment]
Running into a UI bug I'd like a second opinion on. Will bring up during the Hack Night on Friday.

**Comment by nickswalker** [comment]
I have time to look now if you want to push the issue.

**Comment by nickswalker** [comment]
As we talked about, this is now dependent on #26

**Comment by jessetipton** [comment]
I used a bar button instead of one on the detail view so this can probably be merged in #28
