### ISSUE TITLE
Redesign check-in credential

### ISSUE THREAD

**Issue by nickswalker** [utcsmad/uMAD-iOS#31]
We decided to remove polling, and agreed that some work should be done to make the screen more appealing.

**Comment by nickswalker** [comment]
@roonieone can you take this up?

**Comment by roonieone** [comment]
Yeah, I'm on it.

**Comment by nickswalker** [comment]
From mark:
![](https://files.slack.com/files-pri/T0DKB9R50-F0KS7LU9Z/pass.png)

**Comment by jessetipton** [comment]
Boom #47
