### ISSUE TITLE
My Schedule tab

### ISSUE THREAD

**Issue by nickswalker** [utcsmad/uMAD-iOS#33]
Per our discussions we need a tab that displays the sessions that have been favorited, and displays some prompt text for users who haven't favorited anything.

**Comment by roonieone** [comment]
**Images:**

![favorites blank](https://cloud.githubusercontent.com/assets/10133782/12608541/49516f3e-c4a2-11e5-8567-e72bb33ec856.png)
![favorites notification](https://cloud.githubusercontent.com/assets/10133782/12608540/494e2338-c4a2-11e5-9d57-448d6fab03ef.png)
![favorites tab](https://cloud.githubusercontent.com/assets/10133782/12608542/495277ee-c4a2-11e5-929f-2b8334b43dae.png)

**Comment by nickswalker** [comment]
Because of the long workshop names, we won't be able to fit extra text in the cell. Matt and I discussed using a red indicator dot instead.
