### ISSUE TITLE
Done button in Profile view doesn't appear as UIBarButtonItemStyleDone

### ISSUE THREAD

**Issue by roonieone** [utcsmad/uMAD-iOS#35]
The Done button in the Profile view appears as `regular` font weight instead of `semibold` or `bold` (or whatever `UIBarButtonItemStyleDone` is supposed to be). See attached photo.

![simulator screen shot jan 27 2016 2 27 43 am](https://cloud.githubusercontent.com/assets/10133782/12608310/0ad96a32-c4a1-11e5-964e-437cc17bac15.png)

**Comment by nickswalker** [comment]
Fixed on splash branch. I'll close this once it gets merged in.
