### ISSUE TITLE
Search bar in Sessions view is incorrect style

### ISSUE THREAD

**Issue by ghost** [utcsmad/uMAD-iOS#55]
Should be `UISearchBarStyle.Minimal`

**Comment by nickswalker** [comment]
This seems to cause undesired behavior.
![simulator screen shot feb 5 2016 4 41 51 pm](https://cloud.githubusercontent.com/assets/924295/12861207/6358efa6-cc27-11e5-9229-11a289e634a1.png)

**Comment by ghost** [comment]
Unless the style is changed, there will be a visual bug. The style needs to change to resolve this.
![2016-02-05 18 52 23](https://cloud.githubusercontent.com/assets/10133782/12863398/b8af56b2-cc3a-11e5-9546-a1019594d74b.png)

**Comment by nickswalker** [comment]
What's the bug? Changing to `.Minimal` didn't resolve in any improvement, so I'm not sure what bug you're referring to.

**Comment by nickswalker** [comment]
Can you link me to the desired display?

**Comment by ghost** [comment]
Changing the style to `.Minimal` is supposed to change the color of the background to white and the text field to gray. There must be some code somewhere else in the app that is causing the visual bug that appears when the style is `.Minimal`.

The current visual "bug" is yellow text on a gray background—unreadable. Changing the style to `.Minimal` (or going in and manually setting the color of the default search bar style, if need be) will resolve this and make the yellow text appear on a white background, if the current bug with `.Minimal` is resolved.
