### ISSUE TITLE
Refactor to use Fabric timeline controller

### ISSUE THREAD

**Issue by nickswalker** [utcsmad/uMAD-iOS#8]
The twitter pane looks awfully similar to something we need in SURE Walk. We should try to refactor it into it's own module, then attempt to bring it out as a CocoaPod or something. Could be great for us, and a nice thing to put out in the community.

**Comment by nickswalker** [comment]
Looks like Twitter is now providing a really good first party solution. The Android client uses it. We should adopt it too.

**Comment by jessetipton** [comment]
taken care of here 61fe0e04e4e5357b4c03a7c86c769d58cd3b424a
